# 文件路径 .github/workflows/deployment.yml
name: Deployment

on:
  push:
    branches: [source] # only push events on source branch trigger deployment

jobs:
  hexo-deployment:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      # with:
      #   submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install Pandoc
      run: |
        # install pandoc
        curl -s -L https://github.com/jgm/pandoc/releases/download/2.9.2/pandoc-2.9.2-linux-amd64.tar.gz | tar xvzf - -C $RUNNER_TOOL_CACHE/

    # - name: 安装 Hexo
    #   run: |
    #     export TZ='Asia/Shanghai'
    #     npm install hexo-cli -g

    # - name: 缓存 Hexo
    #   uses: actions/cache@v1
    #   id: cache
    #   with:
    #     path: node_modules
    #     key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}

    # - name: 安装依赖
    #   if: steps.cache.outputs.cache-hit != 'true'
    #   run: |
    #     npm install --save

    # - name: 生成静态文件
    #   run: |
    #     hexo clean
    #     hexo generate

    # - name: 部署
    #   run: |
    #     git config --global user.name "purplezi"
    #     git config --global user.email "654762676@qq.com"
    #     git clone https://github.com/purplezi/purplezi.github.io.git .deploy_git
    #     # 此处务必用HTTPS链接。SSH链接可能有权限报错的隐患
    #     # =====注意.deploy_git前面有个空格=====
    #     # 这行指令的目的是clone博客静态文件仓库，防止Hexo推送时覆盖整个静态文件仓库，而是只推送有更改的文件
    #     hexo deploy
        
    # - name: Setup Hexo env
    #   env:
    #     ACTION_DEPLOY_KEY: ${{ secrets.DEPLOY_BLOG }}
    #   run: |
    #     # set up private key for deploy
    #     mkdir -p ~/.ssh/
    #     echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
    #     chmod 700 ~/.ssh
    #     chmod 600 ~/.ssh/id_rsa
    #     ssh-keyscan github.com >> ~/.ssh/known_hosts
    #     # set git infomation
    #     git config --global user.name 'purplezi'
    #     git config --global user.email '654762676@qq.com'
    #     # install dependencies
    #     npm i -g hexo-cli
    #     npm i

    - name: Install dependencies & Generate static files
      run: |
        node -v
        npm i -g hexo-cli
        npm i

    - name: Hexo Generate 
      run: |
        # add pandoc to PATH
        export PATH="$PATH:$RUNNER_TOOL_CACHE/pandoc-2.9.2/bin"
        rm -f .yarnclean
        yarn --frozen-lockfile --ignore-engines --ignore-optional --non-interactive --silent --ignore-scripts --production=false
        rm -rf ./public
        yarn run hexo clean
        yarn run hexo generate 

    # - name: Deploy
    #   run: |
    #     hexo deploy

    - name: Deploy to Github Pages
      env:
        GIT_NAME: purplezi
        GIT_EMAIL: 654762676@qq.com
        REPO: github.com/purplezi/purplezi.github.io
        GH_TOKEN: ${{ secrets.DEPLOY_BLOG }}
      run: |
        cd ./public && git init && git add .
        git config --global user.name $GIT_NAME
        git config --global user.email $GIT_EMAIL
        git commit -m "Site deployed by GitHub Actions"
        git push --force --quiet "https://$GH_TOKEN@$REPO" master:master